sudo: required
services:
  - docker

before_install:
  - docker build -t desli94/ci-cd-setup -f Dockerfile.dev .

script:
  - docker run desli94/ci-cd-setup npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "ci-cd-setup"
  env: "CiCdSetup-env"
  bucket_name: "elasticbeanstalk-eu-west-3-525601169177"
  bucket_path: "ci-cd-setup"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"